-- ================================================================
-- 🚀 SCRIPT ÚNICO - TABELAS: ARMAZÉNS + PRODUTOS
-- Execute no SQL Editor do Supabase (Editor SQL)
-- URL: https://supabase.com/dashboard/project/nawqfidnawokqaheqvar/sql
-- ================================================================


-- ================================================================
-- 📦 TABELA: ARMAZÉNS
-- ================================================================

CREATE TABLE IF NOT EXISTS public.armazens (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id UUID NOT NULL,
    name       TEXT NOT NULL,
    localidade TEXT,
    provincia  TEXT,
    responsavel TEXT,
    contacto   TEXT,
    observacao TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_armazens_empresa_id ON public.armazens (empresa_id);
CREATE INDEX IF NOT EXISTS idx_armazens_created_at ON public.armazens (created_at DESC);

-- Activar RLS
ALTER TABLE public.armazens ENABLE ROW LEVEL SECURITY;

-- Limpar políticas antigas
DROP POLICY IF EXISTS "armazens_isolation"             ON public.armazens;
DROP POLICY IF EXISTS "SAAS_TENANT_ISOLATION_armazens" ON public.armazens;
DROP POLICY IF EXISTS "armazens_select_policy"         ON public.armazens;
DROP POLICY IF EXISTS "armazens_insert_policy"         ON public.armazens;
DROP POLICY IF EXISTS "armazens_update_policy"         ON public.armazens;
DROP POLICY IF EXISTS "armazens_delete_policy"         ON public.armazens;

-- Criar política única multiempresa
CREATE POLICY "SAAS_TENANT_ISOLATION_armazens"
ON public.armazens
FOR ALL
TO authenticated
USING (
    empresa_id = (
        SELECT empresa_id FROM public.perfis
        WHERE id = auth.uid()
        LIMIT 1
    )
)
WITH CHECK (
    empresa_id = (
        SELECT empresa_id FROM public.perfis
        WHERE id = auth.uid()
        LIMIT 1
    )
);

-- Activar Realtime
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime' AND tablename = 'armazens'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.armazens;
    END IF;
END $$;


-- ================================================================
-- 🛒 TABELA: PRODUTOS
-- ================================================================

CREATE TABLE IF NOT EXISTS public.produtos (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id     UUID NOT NULL,
    name           TEXT NOT NULL,
    referente      TEXT,
    barcode        TEXT,
    category       TEXT,
    tipologia      TEXT,
    unit           TEXT DEFAULT 'un',
    price          NUMERIC DEFAULT 0,
    cost_price     NUMERIC DEFAULT 0,
    stock_quantity NUMERIC DEFAULT 0,
    min_stock      NUMERIC DEFAULT 0,
    warehouse_id   INTEGER REFERENCES public.armazens(id) ON DELETE SET NULL,
    image          TEXT,
    image_url      TEXT,
    image_path     TEXT,
    ativo          BOOLEAN DEFAULT true,
    data_registo   TIMESTAMPTZ DEFAULT NOW(),
    created_at     TIMESTAMPTZ DEFAULT NOW(),
    updated_at     TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_produtos_empresa_id   ON public.produtos (empresa_id);
CREATE INDEX IF NOT EXISTS idx_produtos_name         ON public.produtos (name);
CREATE INDEX IF NOT EXISTS idx_produtos_barcode      ON public.produtos (barcode);
CREATE INDEX IF NOT EXISTS idx_produtos_warehouse_id ON public.produtos (warehouse_id);
CREATE INDEX IF NOT EXISTS idx_produtos_ativo        ON public.produtos (ativo);

-- Activar RLS
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;

-- Limpar políticas antigas
DROP POLICY IF EXISTS "produtos_isolation"             ON public.produtos;
DROP POLICY IF EXISTS "SAAS_TENANT_ISOLATION_produtos" ON public.produtos;
DROP POLICY IF EXISTS "produtos_select_policy"         ON public.produtos;
DROP POLICY IF EXISTS "produtos_insert_policy"         ON public.produtos;
DROP POLICY IF EXISTS "produtos_update_policy"         ON public.produtos;
DROP POLICY IF EXISTS "produtos_delete_policy"         ON public.produtos;

-- Criar política única multiempresa
CREATE POLICY "SAAS_TENANT_ISOLATION_produtos"
ON public.produtos
FOR ALL
TO authenticated
USING (
    empresa_id = (
        SELECT empresa_id FROM public.perfis
        WHERE id = auth.uid()
        LIMIT 1
    )
)
WITH CHECK (
    empresa_id = (
        SELECT empresa_id FROM public.perfis
        WHERE id = auth.uid()
        LIMIT 1
    )
);

-- Activar Realtime
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime' AND tablename = 'produtos'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.produtos;
    END IF;
END $$;


-- ================================================================
-- ✅ FIM DO SCRIPT
-- Recarregar schema do PostgREST
-- ================================================================
NOTIFY pgrst, 'reload schema';
