-- ABSOLUTE PRODUCTION FIX: Multi-tenant SaaS (Clientes & Locais)
-- This script fixes RLS, Types, and ID generation

-- 1. UTILITY: IDENTIFY TENANT (Empresa)
CREATE OR REPLACE FUNCTION public.get_auth_empresa_id()
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_empresa_id uuid;
BEGIN
    -- Try Perfil first
    SELECT empresa_id INTO v_empresa_id
    FROM public.perfis
    WHERE id = auth.uid();
    
    -- Try Empresa ownership fallback
    IF v_empresa_id IS NULL THEN
        SELECT id INTO v_empresa_id
        FROM public.empresas
        WHERE auth_user_id = auth.uid()
        LIMIT 1;
    END IF;
    
    RETURN v_empresa_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_auth_empresa_id TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_auth_empresa_id TO service_role;

-- 2. TABLE REPAIR: Clientes
-- Ensure ID is auto-incrementing if it isn't
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'clientes' AND column_name = 'id' AND column_default IS NOT NULL
    ) THEN
        -- Only attempt if it doesn't have a default
        ALTER TABLE public.clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

-- Ensure empresa_id is NOT NULL and correctly typed
ALTER TABLE public.clientes ALTER COLUMN empresa_id SET NOT NULL;

-- 3. TABLE REPAIR: Locais de Trabalho
-- Ensure ID is auto-incrementing
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'locais_trabalho' AND column_name = 'id' AND column_default IS NOT NULL
    ) THEN
        ALTER TABLE public.locais_trabalho ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

ALTER TABLE public.locais_trabalho ALTER COLUMN empresa_id SET NOT NULL;

-- 4. RLS POLICIES (Hardened and Debugged)

-- Clientes
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "SaaS_Clientes_Isolation" ON public.clientes;
CREATE POLICY "SaaS_Clientes_Isolation" ON public.clientes
FOR ALL TO authenticated
USING (empresa_id = public.get_auth_empresa_id())
WITH CHECK (empresa_id = public.get_auth_empresa_id());

-- Locais
ALTER TABLE public.locais_trabalho ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "SaaS_Locais_Isolation" ON public.locais_trabalho;
CREATE POLICY "SaaS_Locais_Isolation" ON public.locais_trabalho
FOR ALL TO authenticated
USING (empresa_id = public.get_auth_empresa_id())
WITH CHECK (empresa_id = public.get_auth_empresa_id());

-- 5. TRIGGER: FORCE empresa_id on INSERT (Fail-safe)
CREATE OR REPLACE FUNCTION public.enforce_empresa_id()
RETURNS TRIGGER AS $$
BEGIN
    -- Force the företag_id to the user's company
    NEW.empresa_id := public.get_auth_empresa_id();
    
    IF NEW.empresa_id IS NULL THEN
        RAISE EXCEPTION 'Acesso Negado: O utilizador não está associado a nenhuma empresa válida.';
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_enforce_empresa_clientes ON public.clientes;
CREATE TRIGGER tr_enforce_empresa_clientes
BEFORE INSERT ON public.clientes
FOR EACH ROW EXECUTE FUNCTION public.enforce_empresa_id();

DROP TRIGGER IF EXISTS tr_enforce_empresa_locais ON public.locais_trabalho;
CREATE TRIGGER tr_enforce_empresa_locais
BEFORE INSERT ON public.locais_trabalho
FOR EACH ROW EXECUTE FUNCTION public.enforce_empresa_id();

-- 6. PERMISSIONS RE-SYNC
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- 7. NOTIFY (to verify in dashboard)
COMMENT ON FUNCTION public.get_auth_empresa_id IS 'Core multi-tenant security function for SaaS isolation.';
