-- 1. Ensure table exists
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='clientes' AND table_schema='public') THEN
        CREATE TABLE public.clientes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            empresa_id UUID NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
            nome TEXT NOT NULL,
            telefone TEXT,
            email TEXT,
            endereco TEXT,
            tipo_entidade TEXT,
            contribuinte TEXT,
            localidade TEXT,
            codigo_postal TEXT,
            provincia TEXT,
            municipio TEXT,
            pais TEXT DEFAULT 'Angola',
            webpage TEXT,
            tipo_cliente TEXT,
            saldo_inicial NUMERIC DEFAULT 0,
            nif TEXT,
            address TEXT,
            initial_balance NUMERIC DEFAULT 0,
            estado_nif TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
        );
    ELSE
        -- Ensure empresa_id exists if table already exists
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='clientes' AND column_name='empresa_id') THEN
            ALTER TABLE public.clientes ADD COLUMN empresa_id UUID REFERENCES public.empresas(id) ON DELETE CASCADE;
        END IF;
    END IF;
END $$;

-- 2. Ativar Row Level Security (RLS)
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Segurança (Isolamento por Empresa)
DROP POLICY IF EXISTS "clientes_select_policy" ON public.clientes;
DROP POLICY IF EXISTS "clientes_insert_policy" ON public.clientes;
DROP POLICY IF EXISTS "clientes_update_policy" ON public.clientes;
DROP POLICY IF EXISTS "clientes_delete_policy" ON public.clientes;

CREATE POLICY "clientes_select_policy" ON public.clientes
    FOR SELECT USING (
        empresa_id = public.get_auth_empresa_id()
    );

CREATE POLICY "clientes_insert_policy" ON public.clientes
    FOR INSERT WITH CHECK (
        empresa_id = public.get_auth_empresa_id()
    );

CREATE POLICY "clientes_update_policy" ON public.clientes
    FOR UPDATE USING (
        empresa_id = public.get_auth_empresa_id()
    );

CREATE POLICY "clientes_delete_policy" ON public.clientes
    FOR DELETE USING (
        empresa_id = public.get_auth_empresa_id()
    );

-- 4. Trigger para atualizar updated_at
CREATE OR REPLACE FUNCTION public.handle_clientes_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_clientes_updated_at ON public.clientes;
CREATE TRIGGER tr_clientes_updated_at BEFORE UPDATE ON public.clientes FOR EACH ROW EXECUTE FUNCTION public.handle_clientes_updated_at();
