-- =========================================================================
-- 1. FIX: TABELA DE ARMAZÉNS (MANTENDO OS DADOS)
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.armazens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id UUID NOT NULL,
    name TEXT NOT NULL,
    localidade TEXT,
    provincia TEXT,
    responsavel TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ADICIONAR COLUNAS FALTANTES SEM APAGAR DADOS (Corrige o erro do "contacto")
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='armazens' AND column_name='contacto') THEN
        ALTER TABLE public.armazens ADD COLUMN contacto TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='armazens' AND column_name='observacao') THEN
        ALTER TABLE public.armazens ADD COLUMN observacao TEXT;
    END IF;
END $$;

ALTER TABLE public.armazens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "SAAS_TENANT_ISOLATION_armazens" ON public.armazens;
CREATE POLICY "SAAS_TENANT_ISOLATION_armazens"
ON public.armazens
FOR ALL TO authenticated
USING (empresa_id = (SELECT empresa_id FROM public.perfis WHERE id = auth.uid()))
WITH CHECK (empresa_id = (SELECT empresa_id FROM public.perfis WHERE id = auth.uid()));

CREATE INDEX IF NOT EXISTS idx_armazens_empresa_id ON public.armazens(empresa_id);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE tablename = 'armazens') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.armazens;
  END IF;
END $$;


-- =========================================================================
-- 2. FIX: TABELA DE ARQUIVOS/MEDIA (BARRA LATERAL E OUTROS)
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.media_arquivos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id UUID NOT NULL,
    utilizador_id UUID,
    tipo TEXT NOT NULL,
    nome_arquivo TEXT NOT NULL,
    nome_original TEXT,
    bucket TEXT,
    caminho_arquivo TEXT,
    url_publica TEXT,
    mime_type TEXT,
    tamanho_bytes BIGINT,
    extensao TEXT,
    entidade TEXT,
    entidade_id TEXT,
    observacao TEXT,
    ativo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.media_arquivos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "SAAS_TENANT_ISOLATION_media_arquivos" ON public.media_arquivos;
CREATE POLICY "SAAS_TENANT_ISOLATION_media_arquivos"
ON public.media_arquivos
FOR ALL TO authenticated
USING (empresa_id = (SELECT empresa_id FROM public.perfis WHERE id = auth.uid()))
WITH CHECK (empresa_id = (SELECT empresa_id FROM public.perfis WHERE id = auth.uid()));

CREATE INDEX IF NOT EXISTS idx_media_empresa_id ON public.media_arquivos(empresa_id);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE tablename = 'media_arquivos') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.media_arquivos;
  END IF;
END $$;

-- =========================================================================
-- 3. FIX: CAIXA MOVIMENTACOES 
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.caixas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id UUID NOT NULL,
    nome_caixa TEXT NOT NULL,
    valor_inicial NUMERIC DEFAULT 0,
    current_balance NUMERIC DEFAULT 0,
    responsavel TEXT,
    utilizador_id UUID,
    observacao TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    account TEXT,
    moeda TEXT DEFAULT 'AOA',
    status TEXT DEFAULT 'aberto'
);

CREATE TABLE IF NOT EXISTS public.caixa_movimentacoes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id UUID NOT NULL,
    caixa_id UUID NOT NULL REFERENCES public.caixas(id) ON DELETE CASCADE,
    target_caixa_id UUID REFERENCES public.caixas(id) ON DELETE SET NULL,
    type TEXT NOT NULL CHECK (type IN ('entrada', 'saida', 'transferencia')),
    amount NUMERIC NOT NULL DEFAULT 0,
    moeda TEXT DEFAULT 'AOA',
    description TEXT,
    date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.caixas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.caixa_movimentacoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "SAAS_TENANT_ISOLATION_caixas" ON public.caixas;
CREATE POLICY "SAAS_TENANT_ISOLATION_caixas"
ON public.caixas
FOR ALL TO authenticated
USING (empresa_id = (SELECT empresa_id FROM public.perfis WHERE id = auth.uid()))
WITH CHECK (empresa_id = (SELECT empresa_id FROM public.perfis WHERE id = auth.uid()));

DROP POLICY IF EXISTS "SAAS_TENANT_ISOLATION_mov" ON public.caixa_movimentacoes;
CREATE POLICY "SAAS_TENANT_ISOLATION_mov"
ON public.caixa_movimentacoes
FOR ALL TO authenticated
USING (empresa_id = (SELECT empresa_id FROM public.perfis WHERE id = auth.uid()))
WITH CHECK (empresa_id = (SELECT empresa_id FROM public.perfis WHERE id = auth.uid()));

CREATE INDEX IF NOT EXISTS idx_caixas_empresa_id ON public.caixas(empresa_id);
CREATE INDEX IF NOT EXISTS idx_caixamov_empresa_id ON public.caixa_movimentacoes(empresa_id);

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE tablename = 'caixas') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.caixas;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE tablename = 'caixa_movimentacoes') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.caixa_movimentacoes;
  END IF;
END $$;

-- Atualizar schema do postgrest para refletir as novas colunas/tabelas
NOTIFY pgrst, 'reload schema';
