-- 1. Limpar policies obsoletas que causam recursão
DROP POLICY IF EXISTS "perfis_select_policy" ON public.perfis;
DROP POLICY IF EXISTS "perfis_update_policy" ON public.perfis;
DROP POLICY IF EXISTS "perfis_select_safe" ON public.perfis;
DROP POLICY IF EXISTS "perfis_insert_safe" ON public.perfis;
DROP POLICY IF EXISTS "perfis_update_safe" ON public.perfis;
DROP POLICY IF EXISTS "perfis_delete_safe" ON public.perfis;

-- 2. Ativar RLS
ALTER TABLE public.perfis ENABLE ROW LEVEL SECURITY;

-- 3. Criar policies seguras (SEM RECURSÃO)
CREATE POLICY "perfis_select_safe" ON public.perfis FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "perfis_insert_safe" ON public.perfis FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "perfis_update_safe" ON public.perfis FOR UPDATE USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "perfis_delete_safe" ON public.perfis FOR DELETE USING (auth.uid() IS NOT NULL);

-- 4. Tabela Clientes
CREATE TABLE IF NOT EXISTS public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    empresa_id UUID REFERENCES public.empresas(id) ON DELETE CASCADE,
    telefone TEXT,
    email TEXT,
    endereco TEXT,
    tipo_entidade TEXT,
    contribuinte TEXT,
    localidade TEXT,
    codigo_postal TEXT,
    provincia TEXT,
    municipio TEXT,
    pais TEXT DEFAULT 'Angola',
    webpage TEXT,
    tipo_cliente TEXT,
    saldo_inicial NUMERIC DEFAULT 0,
    nif TEXT,
    address TEXT,
    initial_balance NUMERIC DEFAULT 0,
    estado_nif TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- 5. Função Empresa Logada
CREATE OR REPLACE FUNCTION public.get_auth_empresa_id()
RETURNS UUID AS $$
BEGIN
  RETURN (
    SELECT empresa_id
    FROM public.perfis
    WHERE id = auth.uid()
    LIMIT 1
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. RLS Clientes
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "clientes_select_policy" ON public.clientes;
DROP POLICY IF EXISTS "clientes_insert_policy" ON public.clientes;
DROP POLICY IF EXISTS "clientes_update_policy" ON public.clientes;
DROP POLICY IF EXISTS "clientes_delete_policy" ON public.clientes;

CREATE POLICY "clientes_select_policy" ON public.clientes FOR SELECT USING (empresa_id = public.get_auth_empresa_id());
CREATE POLICY "clientes_insert_policy" ON public.clientes FOR INSERT WITH CHECK (empresa_id = public.get_auth_empresa_id());
CREATE POLICY "clientes_update_policy" ON public.clientes FOR UPDATE USING (empresa_id = public.get_auth_empresa_id());
CREATE POLICY "clientes_delete_policy" ON public.clientes FOR DELETE USING (empresa_id = public.get_auth_empresa_id());

-- 7. Trigger Atualização Clientes
CREATE OR REPLACE FUNCTION public.handle_clientes_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_clientes_updated_at ON public.clientes;
CREATE TRIGGER tr_clientes_updated_at BEFORE UPDATE ON public.clientes FOR EACH ROW EXECUTE FUNCTION public.handle_clientes_updated_at();
