-- DADOS DA EMPRESA
CREATE TABLE IF NOT EXISTS dados_empresa (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id UUID NOT NULL,
    nome TEXT,
    nif TEXT,
    endereco TEXT,
    telefone TEXT,
    email TEXT,
    logotipo TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE dados_empresa ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "full_access_company" ON dados_empresa;
CREATE POLICY "full_access_company" ON dados_empresa FOR ALL USING (auth.uid() = company_id) WITH CHECK (auth.uid() = company_id);

-- SÉRIES FISCAIS
CREATE TABLE IF NOT EXISTS series_fiscais (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id UUID NOT NULL,
    serie TEXT NOT NULL,
    descricao TEXT,
    tipo TEXT,
    proximo_numero INT DEFAULT 1,
    ativo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE series_fiscais ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "full_access_company" ON series_fiscais;
CREATE POLICY "full_access_company" ON series_fiscais FOR ALL USING (auth.uid() = company_id) WITH CHECK (auth.uid() = company_id);

-- TABELA DE IMPOSTOS
CREATE TABLE IF NOT EXISTS tabela_impostos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id UUID NOT NULL,
    nome TEXT NOT NULL,
    taxa NUMERIC NOT NULL,
    descricao TEXT,
    codigo_imposto TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE tabela_impostos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "full_access_company" ON tabela_impostos;
CREATE POLICY "full_access_company" ON tabela_impostos FOR ALL USING (auth.uid() = company_id) WITH CHECK (auth.uid() = company_id);

-- LOCAIS DE TRABALHO
CREATE TABLE IF NOT EXISTS locais_trabalho (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id UUID NOT NULL,
  nome TEXT,
  endereco TEXT,
  cidade TEXT,
  telefone TEXT,
  email TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE locais_trabalho ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "full_access_company" ON locais_trabalho;
CREATE POLICY "full_access_company" ON locais_trabalho FOR ALL USING (auth.uid() = company_id) WITH CHECK (auth.uid() = company_id);

-- DOCUMENTOS EMITIDOS (VENDAS) 
ALTER TABLE documentos_emitidos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "full_access_company" ON documentos_emitidos;
CREATE POLICY "full_access_company" ON documentos_emitidos FOR ALL USING (auth.uid() = company_id) WITH CHECK (auth.uid() = company_id);
