-- 1. Tabela de Produtos com suporte a imagens e isolamento por empresa
CREATE TABLE IF NOT EXISTS public.produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id UUID NOT NULL, -- UUID da empresa para isolamento total
    name TEXT NOT NULL,
    referente TEXT,
    price DECIMAL(15,2) DEFAULT 0,
    cost_price DECIMAL(15,2) DEFAULT 0,
    stock_quantity DECIMAL(15,3) DEFAULT 0,
    min_stock DECIMAL(15,3) DEFAULT 0,
    category TEXT,
    unit TEXT DEFAULT 'un',
    barcode TEXT,
    data_registo TIMESTAMPTZ DEFAULT NOW(),
    warehouse_id BIGINT,
    image_url TEXT, -- URL pública da imagem
    image_path TEXT, -- Caminho interno no bucket (essencial para delete)
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Habilitar RLS (Row Level Security) - Segurança por Empresa
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Acesso
CREATE POLICY "Produtos: Ver apenas da própria empresa" 
ON public.produtos FOR SELECT 
USING (empresa_id = auth.uid() OR empresa_id IN (SELECT empresa_id FROM perfis WHERE id = auth.uid()));

CREATE POLICY "Produtos: Inserir para a própria empresa" 
ON public.produtos FOR INSERT 
WITH CHECK (empresa_id = auth.uid() OR empresa_id IN (SELECT empresa_id FROM perfis WHERE id = auth.uid()));

CREATE POLICY "Produtos: Atualizar apenas da própria empresa" 
ON public.produtos FOR UPDATE 
USING (empresa_id = auth.uid() OR empresa_id IN (SELECT empresa_id FROM perfis WHERE id = auth.uid()));

CREATE POLICY "Produtos: Apagar apenas da própria empresa" 
ON public.produtos FOR DELETE 
USING (empresa_id = auth.uid() OR empresa_id IN (SELECT empresa_id FROM perfis WHERE id = auth.uid()));

-- 4. Bucket de Storage para Imagens
-- Nota: O bucket deve ser criado no painel do Supabase com o nome 'produtos-imagens'
-- As políticas abaixo devem ser aplicadas nas configurações de storage

/*
-- POLÍTICAS DE STORAGE (Executar na aba SQL se habilitado ou configurar no painel)

CREATE POLICY "Imagens: Ver apenas da própria empresa"
ON storage.objects FOR SELECT
USING ( bucket_id = 'produtos-imagens' AND (storage.foldername(name))[1] = (auth.jwt() ->> 'empresa_id') );

CREATE POLICY "Imagens: Upload apenas para a pasta da própria empresa"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'produtos-imagens' AND (storage.foldername(name))[1] = (auth.jwt() ->> 'empresa_id') );

CREATE POLICY "Imagens: Apagar apenas da própria empresa"
ON storage.objects FOR DELETE
USING ( bucket_id = 'produtos-imagens' AND (storage.foldername(name))[1] = (auth.jwt() ->> 'empresa_id') );
*/
