-- 🚨 TABELA DE ARMAZÉNS SAAS MULTIEMPRESA

CREATE TABLE IF NOT EXISTS public.armazens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id UUID NOT NULL,
    name TEXT NOT NULL,
    localidade TEXT,
    provincia TEXT,
    responsavel TEXT,
    contacto TEXT,
    observacao TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- HABILITAR RLS
ALTER TABLE public.armazens ENABLE ROW LEVEL SECURITY;

-- POLICY MULTIEMPRESA
DROP POLICY IF EXISTS "SAAS_TENANT_ISOLATION_armazens" ON public.armazens;

CREATE POLICY "SAAS_TENANT_ISOLATION_armazens"
ON public.armazens
FOR ALL
TO authenticated
USING (
  empresa_id = (
    SELECT empresa_id
    FROM public.perfis
    WHERE id = auth.uid()
  )
)
WITH CHECK (
  empresa_id = (
    SELECT empresa_id
    FROM public.perfis
    WHERE id = auth.uid()
  )
);

-- PERFORMANCE / ÍNDICES
CREATE INDEX IF NOT EXISTS idx_armazens_empresa_id ON public.armazens(empresa_id);
CREATE INDEX IF NOT EXISTS idx_armazens_created_at ON public.armazens(created_at);

-- REALTIME SUPABASE
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE tablename = 'armazens'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.armazens;
  END IF;
END $$;
